# Generated by Django 4.1.2 on 2023-06-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paywall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_column='page_url', max_length=255, verbose_name='Page URL')),
            ],
        ),
    ]
