# Generated by Django 4.1.2 on 2023-06-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secondary_market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('Seedrs', 'Seedrs'), ('Crowdcube', 'Crowdcube')], max_length=255)),
                ('target', models.DecimalField(decimal_places=2, max_digits=20)),
                ('premoney_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secondary_market.business')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
