# Generated by Django 4.1.2 on 2023-06-07 18:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedrs_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('sm_eligibility', models.BooleanField()),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=255)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('available_shares', models.DecimalField(decimal_places=2, max_digits=20)),
                ('investors_count', models.IntegerField()),
                ('raising_now', models.BooleanField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField()),
                ('trade_volume', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secondary_market.business')),
            ],
        ),
    ]
