# Generated by Django 4.1.2 on 2023-06-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cycles',
            new_name='Cycle',
        ),
    ]
